source "http://torquebox.org/2x/builds/565/gem-repo"
source "http://rubygems.org"

# Declare your gem's dependencies in madmass.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'sqlite3'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug'

gem "socky-client", "0.4.3"
gem "socky-client-rails", "0.4.5"
gem "socky-server", "0.4.1"
gem "madmass", :path => "/Users/vittorio/dev/projects/madmass"
gem "torquebox-rake-support", "2.x.incremental.565"
gem "torquebox", "2.x.incremental.565"
gem "madmass", :git => "git://github.com/algorithmica/madmass.git", :branch => "master"
